//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docspin.Models
{
    using System;
    
    [Flags]
    public enum AccessControlSetting : byte
    {
        None = 0,
        Read = 1,
        Comment = 2,
        Write = 3,
        Move = 4,
        Archival = 5,
        SupervisorOnly = 6
    }
}
