//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docspin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Repository> RepositorySet { get; set; }
        public virtual DbSet<Document> DocumentSet { get; set; }
        public virtual DbSet<RepositorySupervisor> RepositorySupervisorSet { get; set; }
        public virtual DbSet<DocumentVersion> DocumentVersionSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
        public virtual DbSet<RepositoryACL> RepositoryACLSet { get; set; }
        public virtual DbSet<DocumentACL> DocumentACLSet { get; set; }
    }
}
