//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docspin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Filename { get; set; }
    
        public virtual RepositoryDocument RepositoryDocument { get; set; }
        public virtual User Author { get; set; }
    }
}
