//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docspin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentVersion = new HashSet<DocumentVersion>();
            this.Comments = new HashSet<Comment>();
            this.DocumentACL = new HashSet<DocumentACL>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> Description { get; set; }
        public System.DateTime TsCreated { get; set; }
        public System.DateTime TsModified { get; set; }
        public AccessControlSetting ACS { get; set; }
    
        public virtual ICollection<DocumentVersion> DocumentVersion { get; set; }
        public virtual Repository Repository { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<DocumentACL> DocumentACL { get; set; }
    }
}
