//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docspin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepositoryDocument
    {
        public RepositoryDocument()
        {
            this.DocumentVersion = new HashSet<DocumentVersion>();
            this.DocumentComment = new HashSet<DocumentComment>();
            this.DocumentACL = new HashSet<DocumentACL>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime TsCreated { get; set; }
        public System.DateTime TsModified { get; set; }
        public short Property1 { get; set; }
    
        public virtual ICollection<DocumentVersion> DocumentVersion { get; set; }
        public virtual Repository Repository { get; set; }
        public virtual ICollection<DocumentComment> DocumentComment { get; set; }
        public virtual ICollection<DocumentACL> DocumentACL { get; set; }
    }
}
