//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docspin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repository
    {
        public Repository()
        {
            this.RepositorySupervisor = new HashSet<RepositorySupervisor>();
            this.Documents = new HashSet<Document>();
            this.RepositoryACL = new HashSet<RepositoryACL>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public AccessControlSetting ACS { get; set; }
    
        public virtual ICollection<RepositorySupervisor> RepositorySupervisor { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<RepositoryACL> RepositoryACL { get; set; }
    }
}
