//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSpin2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentACL
    {
        public int Id { get; set; }
        public AccessControlSetting ACS { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}
