//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSpin2.Models
{
    using System;
    
    public enum UserRole : byte
    {
        User = 0,
        Moderator = 1,
        Admin = 2
    }
}
